"""tables

Revision ID: b50c5c2fcdc6
Revises: 
Create Date: 2023-05-06 14:55:37.168060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50c5c2fcdc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=70), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_file', sa.Boolean(), nullable=True),
    sa.Column('readed', sa.Boolean(), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_messages_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], name='fk_rooms_users_rooms_room_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_rooms_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message'], ['messages.id'], name='fk_rooms_messages_messages_message_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], name='fk_rooms_messages_rooms_room_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms_messages')
    op.drop_table('rooms_users')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
